name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: VRCGPUTool.slnx
      Test_Project_Path: VRCGPUTool.Tests\VRCGPUTool.Tests.csproj

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Build
        run: dotnet build $env:Solution_Name --configuration $env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Test
        run: >
          dotnet test $env:Test_Project_Path
          --configuration $env:Configuration
          --settings coverage.runsettings
          --collect:"XPlat Code Coverage"
          --results-directory ./coverage
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Upload coverage to Codecov
        if: matrix.configuration == 'Release'
        uses: codecov/codecov-action@v7
        with:
          files: coverage/**/coverage.cobertura.xml
          use_oidc: true
